### ISSUE TITLE
Request to update Registry with latest schemas

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CTDL_Json_Validation_Schema#3]
@coffeejunk I have created a new folder Schema-2017-08-31, for schemas for the next release. 
I updated all the test cases, and changed the latest to point to 8-31. 
All test cases have passed. 

I would like to have the 08-31 schemas promoted to the registry. 
I thought that using a github issue would be a decent means to request and track completion of requests for schema updates. 
Let me know if you would prefer an alternate process. 
Thanks

**Comment by leolara** [comment]
@coffeejunk @cwd-mparsons I created an issue https://github.com/CredentialEngine/CredentialRegistry/issues/131 to have an script so it is faster everytime

**Comment by coffeejunk** [comment]
@leolara We have a script, I haven't updated the schema yet because the changes break our tests and I wanted to fix them first..

**Comment by coffeejunk** [comment]
@cwd-mparsons I've updated the schemas on staging.
